My_Ecom_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name= 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up, name='signup'),
    path ('login/',views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

My_Ecom_Project/App_Order/urls.py
from os import name
from django.urls import path
from App_Order import views


app_name= 'App_Order'


urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

My_Ecom_Project/App_Payment/urls.py
from os import name
from django.urls import path
from App_Payment import views


app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),

]

My_Ecom_Project/App_Shop/urls.py
from os import name
from django.urls import path
from App_Shop import views
app_name= 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.Productdetail.as_view(), name='product_detail'),
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include
#to show media file
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<htm lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge" >
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <title>{% block title_block %} E-com | Bohubrihi {% endblock %}</title>
        <style>
            .card {
                height: 350px;
            }
            .card_product:after{
                content: "";
                display: table;
                clear: both;
                visibility: hidden;
            }
            .card_product .price_new .card_product .price{
                margin-right: 5px;
            }
            .card_product .price_old{
                color: #999;
            }
            .card_product .img_wrap{
                border-radius: 3px 3px 0 0;
                overflow: hidden;
                position: relative;
                height: 220px;
                text-align: center;
            }
            .card_product .img_wrap img{
                max-height: 100%;
                max-width: 100%;
                object-fit: cover;
            }
            .card_product .info_wrap{
                overflow: hidden;
                padding: 15px;
                border-top: 1px solid #eee;
            }
            .card_product .action_wrap{
                padding-top: 4px;
                margin-top: 4px;
            }
            .card_product .bottom_wrap{
                padding: 50px;
                border-top: 1px solid #eee;
            }
            .card_product .title{
                margin-top: 0px;
            }
        </style>
    </head>

    <body>
        {% include 'navbar.html' %}
        <div class="container">
        
            <div class="messages container mt-2">
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                {% endfor %}
                {% endif %}

            </div>

            {% block body_block %}
        
            {% endblock %}

            
        </div>
        
        
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</htm>

My_Ecom_Project/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container">
    <a class="navbar-brand" href="{% url 'App_Shop:home'%}"> Django E-Commerance Project</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" 
    aria-expanded="false" aria-label= " Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'App_Order:cart' %}" class="nav-link">
                        <i class="fa fa-shopping-cart"></i> Cart
                        <span class="badge badge-light">{{request.user | cart_total}}</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a href="" class="nav-link dropdown-toggle" id="navbarDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" 
                    aria-expanded="false">
                    <i class="fas fa-user-tie"></i> 
                    {{request.user.profile.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile'%}">Profile</a>
                        <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
                        <div class="dropdown-divider" ></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary" href="{% url 'App_Login:login'%}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>